### ISSUE TITLE
Is it working under HTML5?

### ISSUE THREAD

**Issue by damiandevil** [getnamo/SocketIOClient-Unreal#94]
hey guys. Trying to connect the project i've created (as simple as it is possible) to my node.js server but not usre it is working. 

I have created build on HTML5 it compiled without any errors but sockets are not connecting it looks like they're even not even working

**Comment by getnamo** [comment]
Using Plugins in ue4 for html5 platform has never been detailed as such that's not a platform we can support at this time. Consider asking Epic for details on how to write plugins for html5 and maybe then we can see what can be done to add it's support.

**Comment by damiandevil** [comment]
Thanks, will try

**Comment by tutkarz** [comment]
I would like to bump this. I tried socketio with 4.22 and still not working after compiling with html and I think it should work because websockets is meant to be used for browser games.
I tried also UEWebsocket mentioned here and it is working fine with 4.22 html compiled game. But it is much simpler and requires much more work that is already done with socketio. That's why I would rather use socketio if it would work.

**Comment by getnamo** [comment]
Could be a good candidate to try to tackle ~ v1.2-1.3 (probably UE4.24 timeline). Seems to require quite a bit of emscripten knowledge (https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html) to figure out how to embed javascript library based on native js to be callable from c++. It appears the above example used the natively supported WebSocket in javascript and exposed it to c++.

Any help is appreciated since this platform mix is a bit out of my depth.

**Comment by getnamo** [comment]
With the platform deprecation https://github.com/kristjanvalur/UEWebsocket is likely the best alternative.
